### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by maximilize** [ammarahm-ed/react-native-ijkvideo#2]
Seems like you hard forked this code from https://github.com/king6cong/react-native-ijkplayer

Maybe you also should rename the package name inside `package.json`. It's somehow confusing to deal with the repo name `react-native-ijkvideo`, but the module name `react-native-ijkplayer`.

**Comment by maximilize** [comment]
However I created the pull request #3

**Comment by ammarahm-ed** [comment]
Yea thanks, actually this is not yet ready to be used. Only the android side is done (almost) I still need to clean it up and complete the ios side too. And yea that needs to be done too. Thanks! When I get some time, I will cover this up ASAP.

**Comment by ammarahm-ed** [comment]
Okay, I have merged this, thanks for the pull request. I will fix the other stuff soon. This library is great, just incomplete at the moment
