### ISSUE TITLE
Keyboard control not working

### ISSUE THREAD

**Issue by maximilize** [ammarahm-ed/react-native-ijkvideo#6]
When the component is created in react, it is not possible to select any buttons via remote control or keyboard anymore. It's like the video component is forcing the keyhandler focus to itself. Do you know a solution for this?

**Comment by ammarahm-ed** [comment]
I dont understand the issue. Which buttons are you talking about? Do you mean the hardware keyboard or remote such as TV? I have not tested it with Android TV etc because I had none.

Also mention if it is on android or iOS

**Comment by maximilize** [comment]
It affects android. Most apps you can control via hardware keyboard or remote control, even on non-android-tv devices. However, it seems that ijk is stealing the keyevents somehow. It makes the navigation via keyboard/remote control impossible while a video is playing.

**Comment by ammarahm-ed** [comment]
@maximilize Since i dont have anything to test I am not sure about it. But i will do my research to see what might be causing such an issue. Currently on the native code, there is no such thing being done by me to control the key events but maybe we need to release them or something.

**Comment by ammarahm-ed** [comment]
@maximilize sync with the latest changes. I think I fixed it but it is untested.

**Comment by ammarahm-ed** [comment]
I have applied the fix, I am closing this now.
